### ISSUE TITLE
Only move scrollbar in the window that is being scrolled

### ISSUE THREAD

**Issue by mhanberg** [ojroques/nvim-scrollbar#1]
## Description

Currently if you have two splits with the same buffer, and scroll one of them, both scroll bars will move.

## Expectation

I would expect the scroll bars would be window local rather than buffer local.

## Note

I really like this plugin because of how minimal it is, thanks! This isn't isn't a big deal, but figured I'd let you know.

![scroll-bar-fail](https://user-images.githubusercontent.com/5523984/191768977-6a28a019-d6ac-4867-92bf-bf79695136a9.gif)

**Comment by ojroques** [comment]
Yes I'm aware of this. The scrollbar is implemented using Neovim's [virtual text](https://jdhao.github.io/2021/09/09/nvim_use_virtual_text/) which allows to place text anywhere in the buffer. But this feature is buffer-specific, that's why the scrollbar is present in both windows if they display the same buffer.

I agree this is quite annoying but unfortunately I have not found any satisfying workaround to this issue yet. You may be interested in other scrollbar plugins (like [nvim-scrollview](dstein64/nvim-scrollview)) that basically creates a floating window that acts as the scrollbar. This solution is more complicated to implement though, that's why I didn't do it here.

If one day Neovim implements window-local virtual text I'll update the plugin :)
